### ISSUE TITLE
Error: API rate limit exceeded

### ISSUE THREAD

**Issue by annawinkler** [hashicorp/copywrite#28]
👋 Hi! We're using this GH action in the [TFE provider](https://github.com/hashicorp/terraform-provider-tfe/blob/e5a76b8b4a4722021a569f6b26c05fc0dd9beb9a/.github/workflows/ci.yml#L12), and with a recent run, I'm seeing the [error](https://github.com/hashicorp/terraform-provider-tfe/actions/runs/4080165773/jobs/7032342246#step:3:6):

```
GET /repos/hashicorp/copywrite/releases/latest - 403 in 119ms
Error: API rate limit exceeded for 40.77.45.146. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

**Comment by CalebAlbers** [comment]
Hey @annawinkler! Thanks for bringing this up. By default, the [hashicorp/setup-copywrite](https://github.com/hashicorp/setup-copywrite) action tries to pull the latest release from GitHub. On occasion, the GitHub runner IPs (esp for public runners) can run into rate limit problems.

The action itself has unused code to support using a GitHub Token to download releases. I'll make some changes to plumb that in so that you can do something like this to provide a token and get around the unauth rate limits:

```yml
 - uses: hashicorp/setup-copywrite@v1
   with:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I should be able to get that knocked out next week and will let you know once it ships!
